# TP 0 - Introduction

## Exercices 1 - 6

Ok.

## Exercice 7

In [94]:
C=[A zeros(3,2); zeros(2,3) eye(2)]

5×5 Array{Float64,2}:
 1.0  2.0  3.0  0.0  0.0
 2.0  3.0  1.0  0.0  0.0
 3.0  1.0  2.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [106]:
repeat([1; 3; 6], inner=[1, 19])

3×19 Array{Int64,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
 6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6

In [153]:
[1, 3, 6] * ones(1, 19)

3×19 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0     3.0  3.0  3.0  3.0  3.0  3.0  3.0
 6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0     6.0  6.0  6.0  6.0  6.0  6.0  6.0

## Exercice 8

In [122]:
M = reshape(1:144, 12, 12)'

12×12 Array{Int64,2}:
   1    2    3    4    5    6    7    8    9   10   11   12
  13   14   15   16   17   18   19   20   21   22   23   24
  25   26   27   28   29   30   31   32   33   34   35   36
  37   38   39   40   41   42   43   44   45   46   47   48
  49   50   51   52   53   54   55   56   57   58   59   60
  61   62   63   64   65   66   67   68   69   70   71   72
  73   74   75   76   77   78   79   80   81   82   83   84
  85   86   87   88   89   90   91   92   93   94   95   96
  97   98   99  100  101  102  103  104  105  106  107  108
 109  110  111  112  113  114  115  116  117  118  119  120
 121  122  123  124  125  126  127  128  129  130  131  132
 133  134  135  136  137  138  139  140  141  142  143  144

In [123]:
M[1:6, 7:12]

6×6 Array{Int64,2}:
  7   8   9  10  11  12
 19  20  21  22  23  24
 31  32  33  34  35  36
 43  44  45  46  47  48
 55  56  57  58  59  60
 67  68  69  70  71  72

In [125]:
M[[1, 2, 5, 6, 9, 10], [1, 2, 5, 6, 9, 10]]

6×6 Array{Int64,2}:
   1    2    5    6    9   10
  13   14   17   18   21   22
  49   50   53   54   57   58
  61   62   65   66   69   70
  97   98  101  102  105  106
 109  110  113  114  117  118

In [162]:
reshape([getindex(M, ij...) for ij in
         [[i, j] for i in 1:12 for j in 1:12 if (i+j) % 2 == 0]],
        6, 12)'

12×6 Array{Int64,2}:
   1    3    5    7    9   11
  14   16   18   20   22   24
  25   27   29   31   33   35
  38   40   42   44   46   48
  49   51   53   55   57   59
  62   64   66   68   70   72
  73   75   77   79   81   83
  86   88   90   92   94   96
  97   99  101  103  105  107
 110  112  114  116  118  120
 121  123  125  127  129  131
 134  136  138  140  142  144